/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('@element-plus/icons-vue')['Back']
    Clock: typeof import('@element-plus/icons-vue')['Clock']
    CollectionTag: typeof import('@element-plus/icons-vue')['CollectionTag']
    Comment: typeof import('@element-plus/icons-vue')['Comment']
    DArrowLeft: typeof import('@element-plus/icons-vue')['DArrowLeft']
    DArrowRight: typeof import('@element-plus/icons-vue')['DArrowRight']
    Delete: typeof import('@element-plus/icons-vue')['Delete']
    EditPen: typeof import('@element-plus/icons-vue')['EditPen']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Expand: typeof import('@element-plus/icons-vue')['Expand']
    HomeFilled: typeof import('@element-plus/icons-vue')['HomeFilled']
    Location: typeof import('@element-plus/icons-vue')['Location']
    Message: typeof import('@element-plus/icons-vue')['Message']
    Phone: typeof import('@element-plus/icons-vue')['Phone']
    Plus: typeof import('@element-plus/icons-vue')['Plus']
    QuestionFilled: typeof import('@element-plus/icons-vue')['QuestionFilled']
    Right: typeof import('@element-plus/icons-vue')['Right']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('@element-plus/icons-vue')['Search']
    SwitchButton: typeof import('@element-plus/icons-vue')['SwitchButton']
    VideoPlay: typeof import('@element-plus/icons-vue')['VideoPlay']
    View: typeof import('@element-plus/icons-vue')['View']
    ZoomIn: typeof import('@element-plus/icons-vue')['ZoomIn']
    ZoomOut: typeof import('@element-plus/icons-vue')['ZoomOut']
  }
}
