export default [
  {
    type: "计算机基础部份",
    questions: ["进程和线程的区别", "进程间的通信", "单核 CPU 如何实现并发", "CPU 调度算法有哪些？", "linux 如何查找你的进程占用的那个端口", "单核服务器连接数超载了怎么办", "请简述一个编译器的执行过程。前端有哪些常见的编译工具？", "什么是编译型语言和解释型语言，他们有什么区别？", "简述 JS 垃圾回收的过程。用什么算法？", "什么是内存泄漏？如何排查？JS 内存泄漏的常见原因？", "简述 JS 运行时的堆栈内存模型？", "冯·诺依曼架构是什么？", "计算机内部为何使用二进制？", "二进制如何表示负数和小数？", "什么是虚拟内存，为何要使用虚拟内存？", "什么是 Unicode 编码？它和常见的 UTF-8 有什么关系？", "简述计算机网络的 OSI 模型", "一个域名对应一个 ip 吗", "UDP 和 TCP 协议的区别？有什么应用场景", "数组和链表有什么区别？从内存结构上来说"],
  },
  {
    type: "HTML & CSS",
    questions: [
      "DOCTYPE 是什么，都有哪些属性？",
      "meta 标签是干什么的，都有什么属性和作用",
      "什么是 DOM ，它和 HTML 有什么区别？",
      "如何理解 HTML5 语义化 ？有哪些常见的语义化标签？",
      "DOM 节点的 attr 和 property 有何区别",
      "如何一次性插入多个 DOM 节点？考虑性能",
      "offsetHeight scrollHeight clientHeight 有什么区别",
      "HTMLCollection 和 NodeList 的区别",
      "Node 和 Element 有什么区别？",
      "开发一个无限下拉加载图片的页面，如何给每个图片绑定 click 事件？",
      "window.onload 和 DOMContentLoaded 的区别是什么？",
      "script 标签放在 head 里，怎么解决加载阻塞的问题",
      "常见的 HTML 标签哪些是 inline 元素，哪些是 block 元素，哪些是 inline-block 元素",
      "常见的 CSS 选择器有哪些？",
      "CSS 盒子模型，尺寸计算",
      "margin 纵向重叠",
      "lineHeight 如何继承？",
      "margin 负值问题",
      "什么是 BFC 如何触发 BFC？",
      "使用 CSS 实现居中对齐，有哪几种方式？",
      "什么是 CSS 定位上下文？absolute 和 relative 分别依据谁来定位？",
      "CSS overflow: hidden display：none 和 visibility: hidden 有什么区别",
      "CSS px % em rem vw/vh 的区别",
      "如何实现 Retina 屏 1px 像素边框",
      "使用 CSS 画一个三角形",
      "如何实现黑白主题变化？",
      "如何实现响应式布局？",
      "如何理解 z-index ？",
      "使用 flex 设计一个“四合院”布局",
      "你用过哪些 CSS 相关的技术，如库、框架、预处理语言、后处理语言等",
    ],
  },
  {
    type: "JS基础",
    questions: [
      "了解哪些最新的 ES 新特性？",
      "typeof 能判断哪些类型",
      "== 和 === 有什么区别？",
      "你熟悉哪些数组 API ？",
      "值类型和引用类型的区别",
      "箭头函数和普通函数的区别",
      "什么时候不能使用箭头函数",
      "for...in 和 for...of 的区别",
      "JS 原型和原型链",
      "JS 继承有几种方式？",
      "JS 作用域和作用域链",
      "JS 自由变量，如何理解",
      "JS 闭包，如何理解",
      "同步和异步有什么区别？异步的意义是什么？",
      "JS Promise 有几种状态？如何变化",
      "JS Promise 使用",
      "async/await 使用",
      "JS 异步执行顺序",
      "宏任务和微任务的区别",
      "描述 Event Loop 运行机制",
      "Set 和 Array 有什么区别",
      "Map 和 Object 有什么区别",
      "setTimeout、requestAnimationFrame 和 requestIdleCallback 有什么区别",
      "写一个验证 email 的正则表达式",
      "JS 模块化规范有哪些？",
      "JS 如何捕获异常？有几种方式？",
      "0.1 + 0.2 === 0.3 表达式返回什么？",
      "如何理解 JS 单线程？",
      "什么是 WebWorker 如何理解它？",
      "JS 如何进行内存管理和垃圾回收？",
      "如何检测 JS 内存泄漏？内存泄漏的场景有哪些？",
      "如何理解 WebAssembly？",
      "JS V8 Nodejs Deno Bun 这几个，他们是什么关系？",
      "有了解过WeakMap吗？WeakMap与Map的区别是什么？",
    ],
  },
  {
    type: "网络部份",
    questions: [
      "TCP 是如何建立连接的，三次握手，四次挥手",
      "HTTP 几个版本的区别",
      "HTTP 常见的状态码",
      "HTTP 常见 Header",
      "URL 包含哪些部分？",
      "GET 和 POST 请求的区别",
      "Ajax Fetch Axios 三者有什么区别？",
      "Fetch 和 XMLHTTPRequest 有什么区别？",
      "什么是 Restful API ？",
      "什么是 GraphQL ？",
      "如何理解 cookie",
      "为何现代浏览器都禁用第三方 cookie",
      "如何理解 Session ？",
      "什么是 JWT 描述它的工作过程",
      "JWT 如何自动更新 token ？",
      "什么是 SSO 单点登录，描述它的工作过程",
      "什么是跨域？如何实现跨域通讯？",
      "HTTP 请求跨域时为何要发送 options 请求",
      "options 请求会携带 cookie 吗",
      "简述浏览器的缓存策略",
      "什么是图片防盗链，如何实现？",
      "简述 HTTPS 加密过程",
      "移动端 H5 如何抓包？",
      "script 标签的 defer 和 async 有什么区别",
      "prefetch 和 dns-prefetch 分别是什么",
      "WebSocket 和 HTTP 协议有什么区别",
      "如何上传文件？使用 fetch 或者 axios",
      "如何上传大文件？",
      "如何实现图片懒加载？",
      "在网络层面可做哪些性能优化？",
    ],
  },
  {
    type: "VUE使用",
    questions: ["🔥Vue3 和 Vue2 的区别有哪些？说几个主要的", "🔥Vue 组件的通讯方式有哪些？", "🔥Vue 组件的生命周期", "Vue 组件在哪个生命周期发送 ajax 请求？", "Vue 父子组件生命周期调用顺序", "🔥v-show 和 v-if 的区别", "为何v-if和v-for不能一起使用？", "computed 和 watch 有什么区别", "🔥watch 和 watchEffect 的区别", "🔥Vue3 ref 和 reactive 如何选择？", "什么是动态组件？如何使用它？", "什么是 slot ，有什么应用场景？", "🚀Vue 项目可做哪些性能优化？", "什么是 nextTick 如何应用它", "使用 Vue3 Composable 组合式函数，实现 useCount", "使用 Vue3 Composable 组合式函数，实现 useRequest", "自定义组件如何实现 v-model", "如何统一监听 Vue 组件报错", "Vuex 中 mutation 和 action 有什么区别？", "Vuex 和 Pinia 有什么区别？", "Vue-router 导航守卫能用来做什么？"],
  },
  {
    type: "VUE原理",
    questions: ["什么是 MVVM", "什么是 VDOM 它和 DOM 有什么关系", "手写 VNode 对象，表示如下 DOM 节点", "Vue 组件初始化的各个阶段都做了什么？", "Vue 如何实现双向数据绑定", "Vue 模板编译的过程", "Vue 响应式原理", "为何 v-for 需要使用 key", "Vue diff 算法的过程", "Vue3 diff 算法做了哪些优化？", "Vue diff 算法和 React diff 算法的区别", "简述 Vue 组件异步更新的过程", "Vue 组件是如何渲染和更新的", "如何实现 keep-alive 缓存机制", "为何 ref 需要 value 属性"],
  },
  {
    type: "微信小程序",
    questions: ["小程序双线程架构", "直接修改 this.data 为何不会触发视图更新？", "setData 底层做了哪些性能优化处理？", "this.setData({ list: largeDataArray }) 有问题吗？", "小程序登录流程", "如何在不发版的情况下实现小程序的 AB 测试？", "小程序的增量更新", "小程序性能优化", "小程序 WXSS 与 CSS 的区别？", "小程序里拿不到 dom 相关的 api ？", "分包加载", "冷启动与热启动的区别", "组件通信方案", "wx:if 与 hidden 的区别", "Taro/Uni-app 跨端原理对比", "Taro 的实现原理"],
  },
  {
    type: "前端工程(脚手架)",
    questions: ["Vite为什么更快？", "vite中如何使用环境变量？", "vite如何实现根据不同环境(qa、dev、prod)加载不同的配置文件？", "简述Vite的依赖预加载机制。", "vite中如何加载、处理静态资源？", "如何在Vite项目中引入CSS预处理器?", "vite中可做的项目优化有哪些？", "简述vite插件开发流程？", "如何在Vite中配置代理？", "Vite如何集成TypeScript？如何配置？", "什么是 Webpack？它的作用是什么？", "如何使用 Webpack 配置多环境的不同构建配置？", "Webpack 的核心概念有哪些？请简单解释。", "如何在 Webpack 中实现 CSS 和 Sass 的处理？", "Webpack 中的入口和出口是什么？", "Webpack 中的 Loaders 和 Plugins 有什么区别", "Webpack中, 如何实现按需加载？", "什么是 Tree Shaking？如何在 Webpack 中启用它？"],
  },
  {
    type: "Nodejs部份",
    questions: ["对 Node.js 的理解", "Node.js 的优缺点", "Node.js 应用场景", "Node.js 的全局对象有哪些？", "Node.js 事件循环机制", "Node.js 中的 process 对象", "Express middleware(中间件) 工作原理", "Koa 洋葱模型", "Koa 与 Express 的区别"],
  },
  {
    type: "交叉面试",
    questions: [
      "求两个数组的交集和并集",
      "数组转树",
      "树转数组",
      "cookie localStorage sessionStorage 三者有什么区别，有什么应用场景？",
      "前端会有哪些安全问题？该如何预防？",
      "常见的 git 命令有哪些？",
      "如何使用 git 多人协作开发？",
      "是否熟悉 Linux 系统，常见的 Linux 命令有哪些？",
      "如何调试前端代码？",
      "移动端 H5 如何抓包网络请求？",
      "网页重绘 repaint 和重排 reflow 有什么区别",
      "网页多标签页之间如何通讯？和 iframe 如何通讯？",
      "什么是 axios 拦截器，能用来做什么？",
      "是否熟悉 Performance API ，是否了解常见的性能指标？",
      "sourcemap 有何作用，如何配置？",
      "什么是 HTTPS 中间人攻击，如何预防",
      "什么是 OOP ，面向对象三要素是什么？",
      "前端常见的设计模式有哪些？以及应用场景",
      "观察者模式和发布订阅模式的区别",
      "后端返回 10w 条数据，前端该如何处理？",
      "一个网页，一开始很流畅，越用越卡顿，你怎么办？",
      "一个 web 系统，加载很慢，交给你来优化，你会怎么办？",
      "你知道哪些前端或 JS 工具链？它们分别什么作用？",
    ],
  },
  {
    type: "前端Leader/大体问题等",
    questions: ["浏览器从输入 url 到显示网页的全过程", "从 0 搭建一个前端项目，需要考虑哪些方面", "如何实现 ajax 并发请求控制？", "React 和 Vue 有什么区别？更擅长哪一个？", "如何做好技术选型？", "如何理解技术方案设计？是否做过技术方案设计？", "线上出了严重 bug 你该如何解决？", "你参与的项目，研发流程是怎样的？", "你如何保障代码质量？", "是否写过单元测试和 e2e 测试？", "自定义 DSL 流程图", "最近在看什么书？或者学什么新技术吗？", "你的缺点是什么？"],
  },
];
